### ISSUE TITLE
Thumbs inside LXImage-qt doesn't work anymore

### ISSUE THREAD

**Issue by fulalas** [lxde/libfm-qt#104] opened 2017-07-20 02:38 UTC
LXImage-qt -> View -> Show Thumbnails. It opens an attached window, but we can't see any icons. This is a very recent regression.

I'm using last git master.

**Comment by tsujan** [comment] 2017-07-20 10:15
Duplicate of https://github.com/lxde/lximage-qt/issues/102

**Closed by tsujan** 2017-07-20 10:15 UTC
